openapi: 3.0.0
info:
  title: Task Management API
  description: API for managing tasks
  version: 1.0.0

paths:
  /tasks:
    get:
      summary: Получить все задания
      responses:
        '200':
          description: Список заданий
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaskCard'

    post:
      summary: Создание новой карточки заданий
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskCardRequest'
      responses:
        '201':
          description: Созданная карточка заданий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskCard'

  /tasks/{lessonId}:
    get:
      summary: Получение карточки задания по lessonId
      parameters:
        - in: path
          name: lessonId
          required: true
          description: ID урока
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Задание для предоставленного lessonId
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задание не найдено для предоставленного lessonId

    patch:
      summary: Обновление карточки задания по lessonId
      parameters:
        - in: path
          name: lessonId
          required: true
          description: ID урока
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Обновленное задание
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: Задание не найдено для предоставленного lessonId

    delete:
      summary: Удаление задания по lessonId
      parameters:
        - in: path
          name: lessonId
          required: true
          description: ID урока
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTaskRequest'
      responses:
        '200':
          description: Задание успешно удалено
        '404':
          description: Задание не найдено для предоставленного lessonId

  /tasks/checkbox:
    post:
      summary: Создание нового чекбокса
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCheckboxRequest'
      responses:
        '201':
          description: Созданный чекбокс
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /tasks/checkbox/{checkboxId}:
    patch:
      summary: Обновление чекбокса по checkboxId
      parameters:
        - in: path
          name: checkboxId
          required: true
          description: ID чекбокса
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCheckboxRequest'
      responses:
        '200':
          description: Обновленный чекбокс
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Checkbox'
    delete:
      summary: Удаление чекбокса по checkboxId
      parameters:
        - in: path
          name: checkboxId
          required: true
          description: ID чекбокса
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteCheckboxRequest'
      responses:
        '200':
          description: Чекбокс успешно удален
        '404':
          description: Чекбокс не найден для предоставленного checkboxId

components:
  schemas:
    TaskCard:
      type: object
      properties:
        _id:
          type: string
          format: uuid
          description: Уникальный идентификатор карточки задания
        date:
          type: string
          format: date
          description: Дата карточки задания
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'

    Task:
      type: object
      properties:
        _id:
          type: string
          format: uuid
          description: Уникальный идентификатор задания
        title:
          type: string
          description: Название задания
        subject:
          type: string
          description: Предмет задания
        teacher:
          type: string
          description: Преподаватель задания
        isDone:
          type: boolean
          description: Указывает, выполнено ли задание
        deadline:
          type: string
          format: date-time
          description: Срок выполнения задания
        description:
          type: string
          description: Описание задания
        checkboxes:
          type: array
          items:
            $ref: '#/components/schemas/Checkbox'
        lessonId:
          type: string
          format: uuid
          description: ID урока

    Checkbox:
      type: object
      properties:
        _id:
          type: string
          format: uuid
          description: Уникальный идентификатор чекбокса
        title:
          type: string
          description: Название чекбокса
        isDone:
          type: boolean
          description: Указывает, выполнен ли чекбокс

    CreateTaskCardRequest:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Дата карточки задания
        task:
          $ref: '#/components/schemas/Task'
      required:
        - date
        - task
        - lessonId

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          description: Обновленное название задания
        subject:
          type: string
          description: Обновленный предмет задания
        teacher:
          type: string
          description: Обновленный преподаватель задания
        isDone:
          type: boolean
          description: Указывает, выполнено ли задание
        deadline:
           type: string
           format: date-time
           description: Обновленный срок выполнения задания
        description:
           type: string
           description: Обновленное описание задания
        lessonId:
           type: string
           format: uuid
           description: ID урока

    CreateCheckboxRequest:
      type: object
      properties:
        title:
          type: string
          description: Название нового чекбокса
        isDone:
          type: boolean
          description: Указывает, выполнен ли новый чекбокс
        lessonId:
          type: string
          format: uuid
          description: ID урока
      required:
        - title
        - isDone
        - lessonId

    UpdateCheckboxRequest:
      type: object
      properties:
        title:
          type: string
          description: Обновленное название чекбокса
        isDone:
          type: boolean
          description: Указывает, выполнен ли чекбокс

    DeleteTaskRequest:
      type: object
      properties:
        date:
          type: string
          format: date
          description: Дата задания, которое нужно удалить
        lessonId:
          type: string
          format: uuid
          description: ID урока
      required:
        - date
        - lessonId

    DeleteCheckboxRequest:
          type: object
          properties:
            checkboxId:
              type: string
              format: uuid
              description: ID урока
          required:
            - lessonId
